-- Parivar Path production schema for Supabase.
-- Apply with `supabase db push`; never run this with the service key from a browser.

create extension if not exists pgcrypto;

create table if not exists public.districts (
  state text not null,
  name text not null,
  primary key (state, name)
);

create table if not exists public.trades (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_local jsonb not null default '{}'::jsonb,
  sector text not null,
  nsqf_level smallint,
  duration_months smallint,
  entry_qualification text,
  safety_notes text,
  job_roles jsonb not null default '[]'::jsonb,
  description_simple jsonb not null default '{}'::jsonb
);

create table if not exists public.providers (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  state text not null,
  district text not null,
  accreditation text,
  fee_inr integer,
  contact text,
  foreign key (state, district) references public.districts(state, name)
);

create table if not exists public.outcomes (
  id bigint generated by default as identity primary key,
  trade_id bigint not null references public.trades(id),
  state text not null,
  district text,
  cohort_year smallint not null,
  placement_rate numeric(5,2),
  avg_start_salary_inr integer,
  salary_3yr_min integer,
  salary_3yr_max integer,
  self_employment_rate numeric(5,2),
  sample_size integer not null check (sample_size >= 0),
  source text not null,
  verified_on date,
  verified boolean not null default false,
  is_synthetic boolean not null default false,
  evidence_url text,
  review_status text not null default 'pending_data_review' check (review_status in ('pending_data_review', 'reviewed', 'rejected')),
  foreign key (state, district) references public.districts(state, name),
  check (placement_rate is null or placement_rate between 0 and 100),
  check (self_employment_rate is null or self_employment_rate between 0 and 100)
);

create table if not exists public.pathways (
  id bigint generated by default as identity primary key,
  from_trade_id bigint not null references public.trades(id),
  step_order smallint not null,
  step_title text not null,
  nsqf_level smallint,
  next_education text,
  typical_role text,
  typical_salary_range text
);

create table if not exists public.schemes (
  id bigint generated by default as identity primary key,
  name text not null,
  state text,
  eligibility jsonb not null default '{}'::jsonb,
  benefit text,
  how_to_apply text,
  official_url text,
  verified boolean not null default false,
  is_synthetic boolean not null default false,
  verified_on date
);

create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  trade_id bigint references public.trades(id),
  district text,
  name text,
  quote jsonb not null default '{}'::jsonb,
  outcome text,
  is_synthetic boolean not null default true,
  verified boolean not null default false
);

create table if not exists public.staff_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'counsellor')),
  language text not null default 'te' check (language in ('en', 'te', 'hi')),
  district text,
  created_at timestamptz not null default now(),
  primary key (user_id, role)
);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  lang text not null check (lang in ('en', 'hi', 'te')),
  state text not null,
  district text not null,
  user_role text not null check (user_role in ('learner', 'parent', 'both')),
  learner_class text not null check (char_length(learner_class) between 1 and 30),
  income_bracket text not null check (char_length(income_bracket) between 1 and 30),
  selected_trade_id bigint references public.trades(id),
  consent boolean not null check (consent),
  created_at timestamptz not null default now(),
  foreign key (state, district) references public.districts(state, name)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.sessions(id) on delete cascade,
  speaker text not null check (speaker in ('learner', 'parent', 'ai', 'counsellor')),
  text text not null check (char_length(text) between 1 and 1000),
  lang text not null check (lang in ('en', 'hi', 'te')),
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.sessions(id) on delete cascade,
  type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.message_analysis (
  message_id bigint primary key references public.messages(id) on delete cascade,
  objection_category text,
  sentiment numeric(4,3) check (sentiment between -1 and 1),
  intent text
);

create table if not exists public.escalations (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.sessions(id) on delete cascade,
  reason text not null check (char_length(reason) between 1 and 1000),
  summary text,
  status text not null default 'new' check (status in ('new', 'assigned', 'contacted', 'resolved', 'closed_no_response')),
  priority text not null default 'normal' check (priority in ('normal', 'high', 'urgent')),
  language text not null default 'te' check (language in ('en', 'te', 'hi')),
  district text,
  sla_due_at timestamptz,
  counsellor_id uuid references auth.users(id),
  callback_slot text,
  created_at timestamptz not null default now(),
  accepted_at timestamptz,
  resolved_at timestamptz,
  resolution_note text,
  family_changed_mind boolean
);

create table if not exists public.escalation_contacts (
  escalation_id bigint primary key references public.escalations(id) on delete cascade,
  callback_phone text not null check (callback_phone ~ '^[6-9][0-9]{9}$'),
  consented boolean not null check (consented),
  expires_at timestamptz not null default (now() + interval '30 days')
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id),
  entity text not null,
  entity_id text not null,
  action text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_session_created_idx on public.messages(session_id, created_at);
create index if not exists sessions_district_idx on public.sessions(district);
create index if not exists outcomes_trade_location_year_idx on public.outcomes(trade_id, state, district, cohort_year desc);
create index if not exists escalations_status_created_idx on public.escalations(status, created_at);
create index if not exists events_session_type_idx on public.events(session_id, type, created_at);
create index if not exists staff_roles_role_district_idx on public.staff_roles(role, district);

create or replace function public.purge_expired_escalation_contacts()
returns integer
language plpgsql security definer set search_path = public
as $$
declare deleted_count integer;
begin
  delete from public.escalation_contacts where expires_at <= now();
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

create or replace function public.is_staff(required_role text default null)
returns boolean
language sql stable security definer set search_path = public, auth
as $$
  select exists (
    select 1 from public.staff_roles r
    where r.user_id = auth.uid()
      and (required_role is null or r.role = required_role)
  )
$$;

create or replace function public.insert_ai_message(
  target_session_id uuid,
  message_text text,
  message_lang text
)
returns public.messages
language plpgsql security definer set search_path = public
as $$
declare inserted public.messages;
begin
  if not exists (select 1 from public.sessions where id = target_session_id and owner_id = auth.uid()) then
    raise exception 'session_not_owned';
  end if;
  insert into public.messages(session_id, speaker, text, lang)
  values (target_session_id, 'ai', message_text, message_lang)
  returning * into inserted;
  return inserted;
end;
$$;

revoke all on function public.insert_ai_message(uuid, text, text) from public, anon;
grant execute on function public.insert_ai_message(uuid, text, text) to authenticated;

alter table public.districts enable row level security;
alter table public.trades enable row level security;
alter table public.providers enable row level security;
alter table public.outcomes enable row level security;
alter table public.pathways enable row level security;
alter table public.schemes enable row level security;
alter table public.stories enable row level security;
alter table public.staff_roles enable row level security;
alter table public.events enable row level security;
alter table public.sessions enable row level security;
alter table public.messages enable row level security;
alter table public.message_analysis enable row level security;
alter table public.escalations enable row level security;
alter table public.escalation_contacts enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists reference_read on public.districts;
create policy reference_read on public.districts for select to anon, authenticated using (true);
drop policy if exists trades_read on public.trades;
create policy trades_read on public.trades for select to anon, authenticated using (true);
drop policy if exists providers_read on public.providers;
create policy providers_read on public.providers for select to anon, authenticated using (true);
drop policy if exists outcomes_read on public.outcomes;
create policy outcomes_read on public.outcomes for select to anon, authenticated using (true);
drop policy if exists pathways_read on public.pathways;
create policy pathways_read on public.pathways for select to anon, authenticated using (true);
drop policy if exists schemes_read on public.schemes;
create policy schemes_read on public.schemes for select to anon, authenticated using (true);
drop policy if exists stories_read on public.stories;
create policy stories_read on public.stories for select to anon, authenticated using (true);
create policy staff_roles_self_read on public.staff_roles for select to authenticated using (user_id = auth.uid());

create policy sessions_owner_read on public.sessions for select to authenticated using (owner_id = auth.uid());
create policy sessions_owner_insert on public.sessions for insert to authenticated with check (owner_id = auth.uid() and consent);
create policy sessions_owner_update on public.sessions for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy sessions_owner_delete on public.sessions for delete to authenticated using (owner_id = auth.uid());

create policy messages_session_read on public.messages for select to authenticated using (
  exists (select 1 from public.sessions s where s.id = session_id and s.owner_id = auth.uid())
  or exists (select 1 from public.escalations e where e.session_id = session_id and e.counsellor_id = auth.uid() and e.status in ('assigned', 'contacted'))
  or public.is_staff('admin')
);
create policy messages_family_insert on public.messages for insert to authenticated with check (
  speaker in ('learner', 'parent') and exists (select 1 from public.sessions s where s.id = session_id and s.owner_id = auth.uid())
);
create policy messages_staff_insert on public.messages for insert to authenticated with check (
  speaker = 'counsellor' and public.is_staff('counsellor') and exists (
    select 1 from public.escalations e where e.session_id = session_id and e.counsellor_id = auth.uid() and e.status in ('assigned', 'contacted')
  )
);

create policy analysis_staff_read on public.message_analysis for select to authenticated using (public.is_staff('admin'));
create policy escalations_owner_read on public.escalations for select to authenticated using (
  session_id in (select id from public.sessions where owner_id = auth.uid())
  or public.is_staff('admin')
  or counsellor_id = auth.uid()
);
create policy escalations_owner_insert on public.escalations for insert to authenticated with check (session_id in (select id from public.sessions where owner_id = auth.uid()));
create policy escalations_staff_update on public.escalations for update to authenticated using (public.is_staff() and (counsellor_id = auth.uid() or public.is_staff('admin')));
create policy events_owner_insert on public.events for insert to authenticated with check (session_id in (select id from public.sessions where owner_id = auth.uid()));
create policy events_owner_read on public.events for select to authenticated using (session_id in (select id from public.sessions where owner_id = auth.uid()) or public.is_staff('admin'));
create policy contacts_owner_insert on public.escalation_contacts for insert to authenticated with check (escalation_id in (select e.id from public.escalations e join public.sessions s on s.id = e.session_id where s.owner_id = auth.uid()));
create policy contacts_assigned_read on public.escalation_contacts for select to authenticated using (escalation_id in (select id from public.escalations where counsellor_id = auth.uid() and status in ('assigned', 'contacted')));
create policy audit_admin_read on public.audit_log for select to authenticated using (public.is_staff('admin'));

revoke all on public.message_analysis from anon, authenticated;
revoke all on public.audit_log from anon, authenticated;
revoke all on public.escalation_contacts from anon;
revoke all on public.staff_roles from anon;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'escalations'
  ) then
    alter publication supabase_realtime add table public.escalations;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end $$;
