-- Additive SIH 26241 contract migration.
-- This is safe to apply after the original Parivar core migration.

alter table if exists public.outcomes add column if not exists verified boolean not null default false;
alter table if exists public.outcomes add column if not exists is_synthetic boolean not null default false;
alter table if exists public.outcomes add column if not exists evidence_url text;
alter table if exists public.outcomes add column if not exists review_status text not null default 'pending_data_review';

alter table if exists public.escalations add column if not exists priority text not null default 'normal';
alter table if exists public.escalations add column if not exists language text not null default 'te';
alter table if exists public.escalations add column if not exists district text;
alter table if exists public.escalations add column if not exists sla_due_at timestamptz;
alter table if exists public.escalations drop constraint if exists escalations_status_check;
alter table if exists public.escalations add constraint escalations_status_check check (status in ('new', 'assigned', 'contacted', 'resolved', 'closed_no_response'));
alter table if exists public.escalations drop constraint if exists escalations_priority_check;
alter table if exists public.escalations add constraint escalations_priority_check check (priority in ('normal', 'high', 'urgent'));

alter table if exists public.escalation_contacts add column if not exists consented boolean not null default false;
alter table if exists public.escalation_contacts add column if not exists expires_at timestamptz not null default (now() + interval '30 days');
alter table if exists public.escalation_contacts drop constraint if exists escalation_contacts_consent_check;
alter table if exists public.escalation_contacts add constraint escalation_contacts_consent_check check (consented) not valid;
alter table if exists public.sessions add column if not exists consent_version text not null default 'v1';
alter table if exists public.sessions add column if not exists consented_at timestamptz not null default now();

create table if not exists public.schemes (
  id bigint generated by default as identity primary key,
  name text not null,
  state text,
  eligibility jsonb not null default '{}'::jsonb,
  benefit text,
  how_to_apply text,
  official_url text,
  verified boolean not null default false,
  is_synthetic boolean not null default false,
  verified_on date
);

create table if not exists public.stories (
  id bigint generated by default as identity primary key,
  trade_id bigint references public.trades(id),
  district text,
  name text,
  quote jsonb not null default '{}'::jsonb,
  outcome text,
  is_synthetic boolean not null default true,
  verified boolean not null default false
);

create table if not exists public.staff_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'counsellor')),
  language text not null default 'te' check (language in ('en', 'te', 'hi')),
  district text,
  created_at timestamptz not null default now(),
  primary key (user_id, role)
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.sessions(id) on delete cascade,
  type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.schemes enable row level security;
alter table public.stories enable row level security;
alter table public.staff_roles enable row level security;
alter table public.events enable row level security;

drop policy if exists schemes_read on public.schemes;
create policy schemes_read on public.schemes for select to anon, authenticated using (true);
drop policy if exists stories_read on public.stories;
create policy stories_read on public.stories for select to anon, authenticated using (true);
drop policy if exists staff_roles_self_read on public.staff_roles;
create policy staff_roles_self_read on public.staff_roles for select to authenticated using (user_id = auth.uid());
drop policy if exists events_owner_insert on public.events;
create policy events_owner_insert on public.events for insert to authenticated with check (session_id in (select id from public.sessions where owner_id = auth.uid()));
drop policy if exists events_owner_read on public.events;
create policy events_owner_read on public.events for select to authenticated using (session_id in (select id from public.sessions where owner_id = auth.uid()));
drop policy if exists sessions_admin_read on public.sessions;
create policy sessions_admin_read on public.sessions for select to authenticated using (public.is_staff('admin'));
drop policy if exists messages_admin_read on public.messages;
create policy messages_admin_read on public.messages for select to authenticated using (public.is_staff('admin'));
drop policy if exists escalations_counsellor_queue_read on public.escalations;
create policy escalations_counsellor_queue_read on public.escalations for select to authenticated using (
  public.is_staff('counsellor') and status = 'new'
);

create index if not exists events_session_type_created_idx on public.events(session_id, type, created_at);
create index if not exists staff_roles_role_district_idx on public.staff_roles(role, district);

create or replace function public.insert_ai_message(
  target_session_id uuid,
  message_text text,
  message_lang text
)
returns public.messages
language plpgsql security definer set search_path = public
as $$
declare inserted public.messages;
begin
  if not exists (select 1 from public.sessions where id = target_session_id and owner_id = auth.uid()) then
    raise exception 'session_not_owned';
  end if;
  insert into public.messages(session_id, speaker, text, lang)
  values (target_session_id, 'ai', message_text, message_lang)
  returning * into inserted;
  return inserted;
end;
$$;

revoke all on function public.insert_ai_message(uuid, text, text) from public, anon;
grant execute on function public.insert_ai_message(uuid, text, text) to authenticated;

create or replace function public.purge_expired_escalation_contacts()
returns integer
language plpgsql security definer set search_path = public
as $$
declare deleted_count integer;
begin
  delete from public.escalation_contacts where expires_at <= now();
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;
