-- Normalized, provenance-first outcome data contract.
-- Quantitative claims must reference a source and an explicit review state.

create table if not exists public.data_sources (
  id bigint generated by default as identity primary key,
  publisher text not null,
  title text not null,
  source_url text,
  document_reference text,
  retrieved_on date,
  created_at timestamptz not null default now(),
  check (source_url is not null or document_reference is not null)
);

create table if not exists public.outcome_metrics (
  id bigint generated by default as identity primary key,
  trade_id bigint not null references public.trades(id) on delete cascade,
  provider_id bigint references public.providers(id) on delete set null,
  state text not null,
  district text,
  metric_key text not null check (metric_key in (
    'placement_rate',
    'starting_earnings',
    'earnings_after_period',
    'self_employment_rate',
    'job_roles',
    'progression',
    'nsqf_level'
  )),
  metric_value numeric,
  metric_text text,
  unit text not null,
  period_start date,
  period_end date,
  year smallint,
  sample_size integer check (sample_size is null or sample_size >= 0),
  source_id bigint not null references public.data_sources(id),
  verification_date date,
  verification_status text not null default 'pending'
    check (verification_status in ('verified', 'pending', 'rejected')),
  data_quality text not null default 'unknown'
    check (data_quality in ('high', 'medium', 'low', 'unknown')),
  confidence numeric(4,3) check (confidence is null or confidence between 0 and 1),
  is_synthetic boolean not null default false,
  created_at timestamptz not null default now(),
  check (metric_value is not null or metric_text is not null),
  check (verification_status <> 'verified' or (
    is_synthetic = false and verification_date is not null
  )),
  check (metric_key not in ('placement_rate', 'self_employment_rate')
    or metric_value between 0 and 100),
  foreign key (state, district) references public.districts(state, name)
);

alter table public.providers add column if not exists verified boolean not null default false;
alter table public.providers add column if not exists is_synthetic boolean not null default false;
alter table public.providers add column if not exists source_id bigint references public.data_sources(id);

alter table public.pathways add column if not exists source_id bigint references public.data_sources(id);
alter table public.pathways add column if not exists verification_status text not null default 'pending'
  check (verification_status in ('verified', 'pending', 'rejected'));
alter table public.pathways add column if not exists is_synthetic boolean not null default false;

alter table public.data_sources enable row level security;
alter table public.outcome_metrics enable row level security;

drop policy if exists data_sources_public_read on public.data_sources;
create policy data_sources_public_read on public.data_sources
  for select to anon, authenticated using (true);

drop policy if exists outcome_metrics_public_read on public.outcome_metrics;
create policy outcome_metrics_public_read on public.outcome_metrics
  for select to anon, authenticated using (true);

create index if not exists outcome_metrics_trade_location_idx
  on public.outcome_metrics(trade_id, state, district, year desc);
create index if not exists outcome_metrics_provider_idx
  on public.outcome_metrics(provider_id, metric_key, year desc);
create index if not exists outcome_metrics_verification_idx
  on public.outcome_metrics(verification_status, is_synthetic, verification_date desc);
create index if not exists outcome_metrics_source_idx
  on public.outcome_metrics(source_id);
create index if not exists providers_location_verified_idx
  on public.providers(state, district, verified, is_synthetic);
create index if not exists pathways_trade_verification_idx
  on public.pathways(from_trade_id, verification_status, is_synthetic, step_order);

create or replace view public.current_outcome_metrics as
select
  m.*,
  s.publisher,
  s.title as source_title,
  s.source_url,
  s.document_reference
from public.outcome_metrics m
join public.data_sources s on s.id = m.source_id
where m.verification_status = 'verified'
  and m.is_synthetic = false;

alter table public.sessions add column if not exists learner_age smallint
  check (learner_age is null or learner_age between 1 and 120);
alter table public.sessions add column if not exists guardian_consent boolean not null default false;
alter table public.sessions add column if not exists concern_state jsonb not null default
  '{"initial_concerns":[],"evidence_presented":[],"current_concerns":[],"unresolved_concerns":[],"escalation_status":"not_escalated"}'::jsonb;
alter table public.sessions add column if not exists joint_counselling_state jsonb not null default
  '{"mode":"not_started","status":"not_started","answers":{},"comparison":null,"counselling_plan":null,"evidence_discussed":[],"unresolved":false,"escalation_status":"not_escalated"}'::jsonb;

alter table public.message_analysis add column if not exists concerns jsonb not null default '[]'::jsonb;
alter table public.message_analysis add column if not exists concern_intensity text not null default 'LOW'
  check (concern_intensity in ('LOW', 'MEDIUM', 'HIGH'));
alter table public.sessions add constraint sessions_guardian_consent_check
  check (learner_age is null or learner_age >= 18 or guardian_consent) not valid;

create or replace function public.purge_expired_family_data()
returns integer
language plpgsql security definer set search_path = public
as $$
declare deleted_count integer;
begin
  delete from public.sessions
  where created_at < now() - interval '730 days'
    and not exists (
      select 1 from public.escalations e
      where e.session_id = sessions.id
        and e.status in ('new', 'assigned', 'contacted')
    );
  get diagnostics deleted_count = row_count;
  perform public.purge_expired_escalation_contacts();
  return deleted_count;
end;
$$;

do $$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron;
    perform cron.schedule(
      'parivar-purge-expired-family-data',
      '17 2 * * *',
      $job$select public.purge_expired_family_data()$job$
    )
    where not exists (
      select 1 from cron.job where jobname = 'parivar-purge-expired-family-data'
    );
  end if;
end;
$$;
